### PR TITLE
fix broken import with pyomo 6.4.3

### LINKED ISSUE #511: pypsa does not work with Pyomo 6.4.3
## Checklist

- [ ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate: 0.21.1

## Describe the Bug

`from pyomo.core.expr.logical_expr import inequality` in `opt.py` produces an error with pyomo 6.4.3

`ImportError: cannot import name 'inequality' from 'pyomo.core.expr.logical_expr'` as it was moved to `pyomo.core.expr.relational_expr`

To fix this, the import should be `from pyomo.environ import inequality` as this is meant as the public import without assuming the internal package structure of pyomo which might change again in the future.
https://github.com/Pyomo/pyomo/blob/main/pyomo/core/tests/unit/test_relational_expr.py#L24

### PR DESCRIPTION
**Pull request by maurerle**
Closes #511  (if applicable).

## Changes proposed in this Pull Request

fix import error by using a less specific import file, which exists in older pyomo versions and the latest version, so that we don't break backwards compatibility.

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and further explanations may be given in `doc`.
- [ ] Unit tests for new features were added (if applicable).
- [ ] Newly introduced dependencies are added to `environment.yaml`, `environment_docs.yaml` and `setup.py` (if applicable).
- [ ] A note for the release notes `doc/release_notes.rst` of the upcoming release is included.
- [x] I consent to the release of this PR's code under the MIT license.

### CODE REVIEW

**Review by fneum — APPROVED** [review]

**Comment by fneum** [comment]
Great! Thanks for the fix!
