### ISSUE TITLE
Export/Import networks from pandapower to pypsa for versions >=2.x

### ISSUE THREAD

**Issue by camiloromers** [PyPSA/PyPSA#123]
I got error when trying to import a network created previously in pandapower 2.x. There are some electrical variables in transformers which are deprecated in pandapower and replace it by other such as s_mva. 

To avoid this issue, I first export it to ppc and the import it using PyPSA but all my nodes are a mess and do not match directly with the ones I have in pandapower.

**Comment by fneum** [comment]
@camiloromers, can you please provide a minimal example to illustrate your issue? Also any detailed error messages are appreciated as requested in the bug report template. Thanks.

**Comment by camiloromers** [comment]
You may use the following code (I am working with PyPSA version 0.16.0 and PandaPower version 2.0.1.)

```
import pandapower as pp
import pandapower.converter as ppc
import pandapower.networks as pn
import pypsa

net = pn.case118()
network = pypsa.Network()
network.import_from_pandapower_net(net)
```

The error I got is: `'DataFrame' object has no attribute 'sn_kva'`. I think is because PandaPower is the latest version decided not to use (sn_kva) and instead (sv_mva).

**Comment by fneum** [comment]
@camiloromers you were right, the transition to pandapower>=2 was incomplete for transformers which are not based on a standard transformer type.

**Comment by fneum** [comment]
Apparently case118 has a lot of unlabeled non-unique components which are necessary for `pypsa`. I would welcome a PR that fixes this, should you want to use case118 nonetheless.

The following works:
```python
import pandapower as pp
import pandapower.converter as ppc
import pandapower.networks as pn
import pypsa

net = pn.create_cigre_network_mv()
network = pypsa.Network()
network.import_from_pandapower_net(net)
