### ISSUE TITLE
pypsa 0.22 doesn't work with matplotlib 3.4.2

### ISSUE THREAD

**Issue by fneum** [PyPSA/PyPSA#558]
(ImportError: cannot import name 'colormaps' from 'matplotlib'), but it does work with 3.6.3 - add to dependencies environment.yaml

**Comment by Shuwei-zhang** [comment]
Ja, genau..

**Comment by Shuwei-zhang** [comment]
Now seems not applied for all new versions..
