### ISSUE TITLE
pypsa does not work with Pyomo 6.4.3

### ISSUE THREAD

**Issue by maurerle** [PyPSA/PyPSA#511]
## Checklist

- [ ] I am using the current [`master`](https://github.com/pypsa/pypsa/tree/master) branch or the latest [release](https://github.com/pypsa/pypsa/releases). Please indicate: 0.21.1

## Describe the Bug

`from pyomo.core.expr.logical_expr import inequality` in `opt.py` produces an error with pyomo 6.4.3

`ImportError: cannot import name 'inequality' from 'pyomo.core.expr.logical_expr'` as it was moved to `pyomo.core.expr.relational_expr`

To fix this, the import should be `from pyomo.environ import inequality` as this is meant as the public import without assuming the internal package structure of pyomo which might change again in the future.
https://github.com/Pyomo/pyomo/blob/main/pyomo/core/tests/unit/test_relational_expr.py#L24
